package AshokIt.exception;

public class exceptionFinally {
    public static void main(String[] args) {
        try{
            int a=10/2;}
//        } catch (Exception e) {
//
//        }
        finally {
            System.out.println("Finally");
        }
    }
}
